[package]
name = "rc"
version = "0.0.1"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
notify-rust = "3.3.0"
linefeed = "0.1.1"
librc = { path = "librc" }
atty = "0.1.2"

[workspace]
members = ["librc"]
